### ISSUE TITLE
cannot find bin/kafka-mqtt-start  command

### ISSUE THREAD

**Issue by pgibert** [kaiwaehner/ksql-udf-deep-learning-mqtt-iot#1]
hello ,
after mvn package 
i cannot find   the command bin/kafka-mqtt-start 
and this not a kafka command .. so wher i can find it please ?

BR

**Comment by pgibert** [comment]
i downloaded the enterprise version and found the kafka-mqtt-start command
but when i start my mosquitto server , ihave problem with the 1883 port already open by the  kafka mqtt proxy?

**Comment by kaiwaehner** [comment]
I added better explanation that the commands are part of CONFLUENT_INSTALL/bin.

How do you start your mosquitto server? Also on Mac with 'brew services start mosquitto'?

This works for me well on two different Mac. Afterwards, I send messages via command:

/usr/local/Cellar/mosquitto/1.4.14_2/bin/mosquitto_pub -h 0.0.0.0 -p 1883 -t car/engine/temperature -q 2 -m "TODO-INPUT-MESSAGE"

You can also try any other MQTT Client to send MQTT messages.

**Comment by pgibert** [comment]
Hello kai ,  thx for the answer
the issue is about mosquito server ….
In your readme , you mention

kafka-mqtt-start kafka-mqtt-quickstart.properties
and then
brew services start mosquito
………………… and  if follow your README I got a problem of address/port already bind
starting firstly the kafka  mqtt proxy opens the port ( OK)  and then my mosquito server cannot start on 1883 (NOT OK)

Did I miss something☺ ? -  I know quite well mosquito pub/sub and server and confluent suite …

My HW/SW is Ubuntu+confluent5.0.0  on a  VM

-------------------------------------------------------------------
Vm1$ kafka-mqtt-start kafka-mqtt-quickstart.properties
[2018-08-02 12:09:50,788] [kafka-mqtt-network-thread-1-1] INFO ProducerConfig values:
        acks = 0
        batch.size = 16384
        bootstrap.servers = [PLAINTEXT://localhost:9092]
       confluent.topic.replication.factor = 1
        listeners = 0.0.0.0:1883
        listeners.security.protocol = PLAINTEXT
        listeners.ssl.cipher.suites = null
……………………
………………………
And then
Vm1$  /usr/sbin/mosquitto -c /etc/mosquitto/mosquitto.conf
1533211920: mosquitto version 0.15 (build date 2017-06-30 22:26:39+0000) starting
1533211920: Opening ipv4 listen socket on port 1883.
1533211920: Error: Address already in use

Best regards
phil

**Comment by kaiwaehner** [comment]
I improved the docs once again. 

After talking to my colleagues, they also said that Mosqitto server and MQTT Proxy share the same default port. Very strange that I do NOT have this issue even if I start both after each other. 

Anyway, the solution:

You don’t need to start the MQTT Broker! You just use Moquitto later to produce MQTT messages via 'mosquitto_pub' command. If you (want to) start Moquitto server), you might get a port issue with MQTT Proxy, in that case change the default port of Mosquitto server.

Event without starting the Mosquitto server, the following should work (without port issues because you only start Confluent MQTT Proxy):

/usr/local/Cellar/mosquitto/1.4.14_2/bin/mosquitto_pub -h 0.0.0.0 -p 1883 -t car/engine/temperature -q 2 -m "99999,2.10# 2.13# 2.19# 2.28# 2.44# 2.62# 2.80# 3.04# 3.36# 3.69# 3.97# 4.24# 4.53#4.80# 5.02# 5.21# 5.40# 5.57# 5.71# 5.79# 5.86# 5.92# 5.98# 6.02# 6.06# 6.08# 6.14# 6.18# 6.22# 6.27#6.32# 6.35# 6.38# 6.45# 6.49# 6.53# 6.57# 6.64# 6.70# 6.73# 6.78# 6.83# 6.88# 6.92# 6.94# 6.98# 7.01#7.03# 7.05# 7.06# 7.07# 7.08# 7.06# 7.04# 7.03# 6.99# 6.94# 6.88# 6.83# 6.77# 6.69# 6.60# 6.53# 6.45#6.36# 6.27# 6.19# 6.11# 6.03# 5.94# 5.88# 5.81# 5.75# 5.68# 5.62# 5.61# 5.54# 5.49# 5.45# 5.42# 5.38#5.34# 5.31# 5.30# 5.29# 5.26# 5.23# 5.23# 5.22# 5.20# 5.19# 5.18# 5.19# 5.17# 5.15# 5.14# 5.17# 5.16#5.15# 5.15# 5.15# 5.14# 5.14# 5.14# 5.15# 5.14# 5.14# 5.13# 5.15# 5.15# 5.15# 5.14# 5.16# 5.15# 5.15#5.14# 5.14# 5.15# 5.15# 5.14# 5.13# 5.14# 5.14# 5.11# 5.12# 5.12# 5.12# 5.09# 5.09# 5.09# 5.10# 5.08# 5.08# 5.08# 5.08# 5.06# 5.05# 5.06# 5.07# 5.05# 5.03# 5.03# 5.04# 5.03# 5.01# 5.01# 5.02# 5.01# 5.01#5.00# 5.00# 5.02# 5.01# 4.98# 5.00# 5.00# 5.00# 4.99# 5.00# 5.01# 5.02# 5.01# 5.03# 5.03# 5.02# 5.02#5.04# 5.04# 5.04# 5.02# 5.02# 5.01# 4.99# 4.98# 4.96# 4.96# 4.96# 4.94# 4.93# 4.93# 4.93# 4.93# 4.93# 5.02# 5.27# 5.80# 5.94# 5.58# 5.39# 5.32# 5.25# 5.21# 5.13# 4.97# 4.71# 4.39# 4.05# 3.69# 3.32# 3.05#2.99# 2.74# 2.61# 2.47# 2.35# 2.26# 2.20# 2.15# 2.10# 2.08"

**Comment by pgibert** [comment]
Hello Kai, thx a lot for your time ☺
…  it was also my understanding to not have the mosquito server to be started…..
I will go with your fixes/recommendations  and finished my test .

Phil
BR

**Comment by pgibert** [comment]
Hello Kai, I confirm . it works nicely ….. with the mosquito pub and also with the sensor script
Again thx a lot
Phil
BR

**Comment by kaiwaehner** [comment]
Great that it works now. 

Please let us know if you have any feedback / improvement proposals regarding MQTT Proxy. Of course, it is a first release. Many new features like publish AND subscribe or additional security options will come soon anyway :-)
